import { databaseConfigured,prisma } from "@/lib/db/prisma";
import { todayActivities } from "@/lib/demo-data";
const hotelSlug="marhaba-salem-resort";
const startOfDay=(d=new Date())=>new Date(d.getFullYear(),d.getMonth(),d.getDate());
const endOfDay=(d=new Date())=>new Date(d.getFullYear(),d.getMonth(),d.getDate()+1);
export const fallbackPlaces=["Réception","Plage de l’hôtel","Restaurant principal","La Pergola","Lobby Bar Obsolut","Café maure","Bar piscine Oxygen","Sol & Sombra","Piscines extérieures","Piscine d’eau de mer et toboggans","Piscine couverte chauffée","Jacuzzi","Salle de sport","Espace bien-être","Mini Club"].map((name,i)=>({id:`place-${i}`,name,slug:name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),description:`Découvrez ${name} au Marhaba Salem Resort.`,imageUrl:i===1?"/images/marhaba-beach.webp":i===8?"/images/marhaba-pool.webp":null,openingHours:null,facilities:[],floor:0,isActive:true,category:null}));
export async function getHotel(){if(!databaseConfigured)return null;try{return await prisma.hotel.findUnique({where:{slug:hotelSlug}})}catch{return null}}
export async function getPlaces(){if(!databaseConfigured)return fallbackPlaces;try{return await prisma.place.findMany({where:{hotel:{slug:hotelSlug},isActive:true},include:{category:true},orderBy:{name:"asc"}})}catch{return fallbackPlaces}}
export async function getPlace(slug:string){if(!databaseConfigured)return fallbackPlaces.find(p=>p.slug===slug)??null;try{return await prisma.place.findUnique({where:{hotelId_slug:{hotelId:(await getHotel())?.id??"",slug}},include:{category:true}})}catch{return fallbackPlaces.find(p=>p.slug===slug)??null}}
export async function getTodayActivities(){if(databaseConfigured)try{const rows=await prisma.activity.findMany({where:{hotel:{slug:hotelSlug},isActive:true,startAt:{gte:startOfDay(),lt:endOfDay()}},include:{place:true},orderBy:{startAt:"asc"}});if(rows.length)return rows.map(r=>({...r,location:r.place?.name??r.locationLabel}));}catch{}const base=startOfDay();return todayActivities.map((a,i)=>{const [h,m]=a.time.split(":").map(Number);const startAt=new Date(base);startAt.setHours(h,m);return{id:`demo-${i}`,title:a.title,description:"Programme de démonstration modifiable depuis l’administration.",startAt,endAt:new Date(startAt.getTime()+3600000),location:a.location,locationLabel:a.location,category:i<2?"SPORT":"ENTERTAINMENT",isFeatured:i===2,isActive:true,place:null,imageUrl:null}})}
export async function getAnnouncements(){if(databaseConfigured)try{return await prisma.announcement.findMany({where:{hotel:{slug:hotelSlug},isActive:true,startsAt:{lte:new Date()},OR:[{endsAt:null},{endsAt:{gte:new Date()}}]},orderBy:[{isFeatured:"desc"},{priority:"desc"},{startsAt:"desc"}]})}catch{}return[{id:"announcement-demo",title:"Ce soir : soirée tunisienne",content:"Buffet spécial et animation live à partir de 19h30. Contenu de démonstration.",type:"EVENT",priority:"HIGH",isFeatured:true,startsAt:new Date(),endsAt:null,isActive:true,imageUrl:null}]}
export async function getDining(){if(databaseConfigured)try{const restaurants=await prisma.restaurant.findMany({where:{hotel:{slug:hotelSlug},isActive:true},include:{place:true},orderBy:{name:"asc"}});const menus=await prisma.menu.findMany({where:{restaurant:{hotel:{slug:hotelSlug}},date:startOfDay(),isActive:true},include:{restaurant:true,items:{where:{isAvailable:true},orderBy:{sortOrder:"asc"}}},orderBy:{mealType:"asc"}});return{restaurants,menus}}catch{}return{restaurants:[],menus:[]}}
export async function getInformation(){if(databaseConfigured)try{return await prisma.hotelInformation.findMany({where:{hotel:{slug:hotelSlug},isActive:true},orderBy:{sortOrder:"asc"}})}catch{}return[]}
export async function searchHotel(query:string){const q=query.trim();if(q.length<2)return[];const places=await getPlaces();const normalized=q.toLocaleLowerCase("fr");const local=places.filter(p=>(p.name+" "+(p.description??"")).toLocaleLowerCase("fr").includes(normalized)).map(p=>({id:p.id,type:"Lieu",title:p.name,description:p.description??"",href:`/places/${p.slug}`}));if(!databaseConfigured)return local;try{const [restaurants,information]=await Promise.all([prisma.restaurant.findMany({where:{hotel:{slug:hotelSlug},isActive:true,OR:[{name:{contains:q,mode:"insensitive"}},{description:{contains:q,mode:"insensitive"}}]}}),prisma.hotelInformation.findMany({where:{hotel:{slug:hotelSlug},isActive:true,OR:[{title:{contains:q,mode:"insensitive"}},{content:{contains:q,mode:"insensitive"}}]}})]);return [...local,...restaurants.map(r=>({id:r.id,type:"Restaurant",title:r.name,description:r.description??r.cuisine??"",href:"/dining#venues"})),...information.map(i=>({id:i.id,type:"Information",title:i.title,description:i.content,href:"/info"}))]}catch{return local}}
export async function getAdminDashboard(){const [activities,announcements,places,dining]=await Promise.all([getTodayActivities(),getAnnouncements(),getPlaces(),getDining()]);return{activities,announcements,counts:{activities:activities.length,announcements:announcements.length,places:places.length,restaurants:dining.restaurants.length}}}
