import { ActivityCategory, AnnouncementPriority, AnnouncementType, InformationType, MealType, PrismaClient } from "@prisma/client";
const db=new PrismaClient();
const schedule={source:"demo",mon:[{open:"08:00",close:"23:00"}],tue:[{open:"08:00",close:"23:00"}],wed:[{open:"08:00",close:"23:00"}],thu:[{open:"08:00",close:"23:00"}],fri:[{open:"08:00",close:"23:00"}],sat:[{open:"08:00",close:"23:00"}],sun:[{open:"08:00",close:"23:00"}]};
async function main(){const hotel=await db.hotel.upsert({where:{slug:"marhaba-salem-resort"},update:{name:"Marhaba Salem Resort"},create:{name:"Marhaba Salem Resort",slug:"marhaba-salem-resort",address:"Boulevard du 14 Janvier, 4039 Sousse, Tunisie"}});await db.activity.deleteMany({where:{hotelId:hotel.id}});await db.announcement.deleteMany({where:{hotelId:hotel.id}});await db.hotelInformation.deleteMany({where:{hotelId:hotel.id}});await db.restaurant.deleteMany({where:{hotelId:hotel.id}});await db.place.deleteMany({where:{hotelId:hotel.id}});await db.placeCategory.deleteMany({where:{hotelId:hotel.id}});const category=await db.placeCategory.create({data:{hotelId:hotel.id,name:"Services & loisirs",slug:"services-loisirs"}});const definitions=[
  ["Réception","reception",null],["Plage de l’hôtel","private-beach","/images/marhaba-beach.webp"],["Restaurant principal","main-restaurant","/images/marhaba-dining.webp"],["La Pergola","la-pergola",null],["Lobby Bar Obsolut","lobby-bar-obsolut",null],["Café maure","moorish-cafe",null],["Bar piscine Oxygen","oxygen-pool-bar",null],["Sol & Sombra","sol-sombra",null],["Restaurant & Bar plage","beach-restaurant-bar",null],["Piscines extérieures","outdoor-pools","/images/marhaba-pool.webp"],["Piscine d’eau de mer et toboggans","seawater-pool-slides",null],["Piscine couverte chauffée","indoor-pool",null],["Jacuzzi","jacuzzi",null],["Salle de sport","fitness",null],["Espace bien-être","wellness",null],["Mini Club","kids-club",null]
] as const;const places=[];for(const [name,slug,imageUrl] of definitions)places.push(await db.place.create({data:{hotelId:hotel.id,categoryId:category.id,name,slug,imageUrl,description:`Découvrez ${name} au Marhaba Salem Resort.`,facilities:[],openingHours:schedule,mapX:15+places.length*4,mapY:24+places.length*3,mapNodeId:`node-${places.length+1}`}}));
const restaurantDefs=[["Restaurant principal","restaurant-principal","Buffet international et tunisien",2],["La Pergola","la-pergola","Restaurant à thème",3],["Lobby Bar Obsolut","lobby-bar-obsolut","Cocktails et rafraîchissements",4],["Café maure","cafe-maure","Ambiance traditionnelle",5],["Oxygen","oxygen","Bar piscine saisonnier",6],["Sol & Sombra","sol-sombra","Snack bar plage saisonnier",7],["Restaurant & Bar plage","restaurant-bar-plage","En bord de mer, en saison",8]] as const;const restaurants=[];for(const [name,slug,cuisine,index] of restaurantDefs)restaurants.push(await db.restaurant.create({data:{hotelId:hotel.id,placeId:places[index].id,name,slug,cuisine,description:cuisine,openingHours:schedule}}));
const date=new Date();date.setHours(0,0,0,0);const menuData=[[MealType.BREAKFAST,"Petit-déjeuner",["Viennoiseries et pains","Fruits frais","Œufs préparés minute"]],[MealType.LUNCH,"Déjeuner",["Salade méchouia","Poisson du jour","Fruits de saison"]],[MealType.DINNER,"Dîner tunisien",["Couscous aux légumes","Grillades méditerranéennes","Pâtisseries tunisiennes"]]] as const;for(const [mealType,title,names] of menuData)await db.menu.create({data:{restaurantId:restaurants[0].id,title,date,mealType,items:{create:names.map((name,i)=>({name,description:"Élément de démonstration, modifiable par l’hôtel.",category:i===2?"Dessert":"Plat",allergens:[],dietaryTags:[],isVegetarian:i!==1,sortOrder:i}))}}});
const activities=[
  ["Aqua Gym",10,ActivityCategory.SPORT,9],["Beach-volley",15,ActivityCategory.SPORT,1],["Activités Mini Club",16,ActivityCategory.KIDS,15],["Musique live",20,ActivityCategory.NIGHTLIFE,4],["Spectacle du soir",22,ActivityCategory.ENTERTAINMENT,4]
] as const;for(const [title,hour,categoryValue,index] of activities){const startAt=new Date();startAt.setHours(hour,0,0,0);await db.activity.create({data:{hotelId:hotel.id,placeId:places[index].id,title,description:"Programme de démonstration, modifiable depuis l’administration.",category:categoryValue,startAt,endAt:new Date(startAt.getTime()+3600000),locationLabel:places[index].name,isFeatured:hour===20}})}
const now=new Date(),tomorrow=new Date(now.getTime()+86400000);for(const data of [{title:"Soirée tunisienne",content:"Buffet spécial et animation live à partir de 19h30. Programme de démonstration.",type:AnnouncementType.EVENT,priority:AnnouncementPriority.HIGH,isFeatured:true},{title:"Programme Mini Club",content:"Activités adaptées aux enfants de 4 à 12 ans.",type:AnnouncementType.INFORMATION,priority:AnnouncementPriority.NORMAL,isFeatured:false},{title:"Confort plage & piscines",content:"Serviettes, chaises longues et parasols sont à disposition.",type:AnnouncementType.POOL,priority:AnnouncementPriority.NORMAL,isFeatured:false}])await db.announcement.create({data:{hotelId:hotel.id,...data,startsAt:now,endsAt:tomorrow}});
await db.hotelInformation.createMany({data:[{hotelId:hotel.id,type:InformationType.WIFI,title:"Wi-Fi",content:"Accès internet Wi-Fi disponible. Demandez les identifiants à la réception."},{hotelId:hotel.id,type:InformationType.RECEPTION,title:"Réception",content:"Ouverte 24h/24 · +216 73 241 966",sortOrder:1},{hotelId:hotel.id,type:InformationType.GENERAL,title:"Adresse",content:"Boulevard du 14 Janvier, 4039 Sousse, Tunisie",sortOrder:2},{hotelId:hotel.id,type:InformationType.EMERGENCY,title:"Urgence",content:"Contactez immédiatement la réception au +216 73 241 966.",sortOrder:3}]});}
main().finally(()=>db.$disconnect());
