import { PrismaClient, MealType, AnnouncementPriority, InformationType } from "@prisma/client";
const db = new PrismaClient();
async function main(){
  const hotel=await db.hotel.upsert({where:{slug:"marhaba-salem-resort"},update:{},create:{name:"Marhaba Salem Resort",slug:"marhaba-salem-resort",address:"Boulevard du 14 Janvier, 4039 Sousse, Tunisie"}});
  const category=await db.placeCategory.upsert({where:{hotelId_slug:{hotelId:hotel.id,slug:"guest-facilities"}},update:{},create:{hotelId:hotel.id,name:"Guest facilities",slug:"guest-facilities"}});
  const names=["Réception","Plage de l’hôtel","Restaurant principal","La Pergola","Lobby Bar Obsolut","Café maure","Bar piscine Oxygen","Snack Bar plage Sol & Sombra","Restaurant & Bar plage","Piscines extérieures","Piscine d’eau de mer et toboggans","Piscine couverte chauffée","Jacuzzi","Salle de sport","Espace bien-être","Mini Club"];
  const places=await Promise.all(names.map((name,index)=>db.place.upsert({where:{hotelId_slug:{hotelId:hotel.id,slug:name.toLowerCase().replaceAll(" ","-")}},update:{},create:{hotelId:hotel.id,categoryId:category.id,name,slug:name.toLowerCase().replaceAll(" ","-"),description:`Discover ${name}, thoughtfully designed for an effortless stay.`,mapX:18+index*7,mapY:30+index*4,floor:0,mapNodeId:`node-${index+1}`}})));
  const mainRestaurant=await db.restaurant.upsert({where:{hotelId_slug:{hotelId:hotel.id,slug:"restaurant-principal"}},update:{},create:{hotelId:hotel.id,placeId:places[2].id,name:"Restaurant principal",slug:"restaurant-principal",cuisine:"Buffet, cuisine internationale et tunisienne"}});
  const venues=[["La Pergola","la-pergola","Restaurant à thème",3],["Lobby Bar Obsolut","lobby-bar-obsolut","Cocktails et rafraîchissements",4],["Café maure","cafe-maure","Café traditionnel",5],["Oxygen","oxygen","Bar piscine saisonnier",6],["Sol & Sombra","sol-et-sombra","Snack bar plage saisonnier",7],["Restaurant & Bar plage","restaurant-bar-plage","Établissement saisonnier",8]] as const;
  await Promise.all(venues.map(([name,slug,cuisine,index])=>db.restaurant.upsert({where:{hotelId_slug:{hotelId:hotel.id,slug}},update:{},create:{hotelId:hotel.id,placeId:places[index].id,name,slug,cuisine}})));
  const date=new Date(); date.setHours(0,0,0,0);
  const menu=await db.menu.create({data:{restaurantId:mainRestaurant.id,title:"Mediterranean Dinner",date,mealType:MealType.DINNER,items:{create:[{name:"Coastal catch of the day",description:"Charred lemon and garden herbs",category:"Main",allergens:["fish"],dietaryTags:[],sortOrder:1},{name:"Saffron vegetable risotto",description:"Local vegetables and aged parmesan",category:"Main",allergens:["milk"],dietaryTags:["vegetarian"],sortOrder:2},{name:"Citrus olive oil cake",description:"Orange blossom and pistachio",category:"Dessert",allergens:["nuts","gluten"],dietaryTags:["vegetarian"],sortOrder:3}]}}});
  if(!menu) throw new Error("Menu seed failed");
  const activities=[["Aqua Gym",10,places[9]],["Beach-volley",15,places[1]],["Activités Mini Club",16,places[15]],["Musique live",20,places[4]],["Spectacle du soir",22,places[4]]] as const;
  await db.activity.createMany({data:activities.map(([title,hour,place])=>{const startAt=new Date();startAt.setHours(hour,0,0,0);const endAt=new Date(startAt.getTime()+60*60*1000);return{hotelId:hotel.id,placeId:place.id,title,description:`Programme de démonstration : ${title.toLowerCase()}.`,startAt,endAt,locationLabel:place.name}})});
  const startsAt=new Date();const endsAt=new Date(startsAt.getTime()+24*60*60*1000);await db.announcement.create({data:{hotelId:hotel.id,title:"Tonight: Mediterranean Night",content:"Special buffet and live entertainment from 19:30.",priority:AnnouncementPriority.HIGH,startsAt,endsAt}});
  await db.hotelInformation.createMany({data:[{hotelId:hotel.id,type:InformationType.WIFI,title:"Wi-Fi",content:"Accès Wi-Fi disponible. Demandez les identifiants à la réception."},{hotelId:hotel.id,type:InformationType.RECEPTION,title:"Réception",content:"Ouverte 24h/24 · +216 73 241 966"},{hotelId:hotel.id,type:InformationType.GENERAL,title:"Adresse",content:"Boulevard du 14 Janvier, 4039 Sousse, Tunisie"}]});
}
main().finally(()=>db.$disconnect());
