CREATE TYPE "ActivityCategory" AS ENUM ('SPORT', 'KIDS', 'ENTERTAINMENT', 'WELLNESS', 'FOOD', 'NIGHTLIFE');
CREATE TYPE "AnnouncementType" AS ENUM ('INFORMATION', 'EVENT', 'DINING', 'POOL', 'WEATHER', 'MAINTENANCE', 'IMPORTANT');
ALTER TABLE "Place" ADD COLUMN "facilities" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Restaurant" ADD COLUMN "openingHours" JSONB;
ALTER TABLE "MenuItem" ADD COLUMN "isVegetarian" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "isSpicy" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "imageUrl" TEXT;
ALTER TABLE "Activity" ADD COLUMN "category" "ActivityCategory" NOT NULL DEFAULT 'ENTERTAINMENT', ADD COLUMN "isFeatured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Announcement" ADD COLUMN "type" "AnnouncementType" NOT NULL DEFAULT 'INFORMATION', ADD COLUMN "isFeatured" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "imageUrl" TEXT;
