export type MapCategory="Restaurants"|"Bars"|"Piscines"|"Activités"|"Services";
export type MapNode={id:string;placeSlug?:string;x:number;y:number;type:"destination"|"junction";name:string;shortName?:string;category?:MapCategory;description?:string};
export type MapEdge={from:string;to:string;seconds:number;instruction:string};
export const mapNodes:MapNode[]=[
{id:"reception",placeSlug:"reception",x:250,y:145,type:"destination",name:"Réception",category:"Services",description:"Lobby et accueil principal"},{id:"lobby",x:250,y:210,type:"junction",name:"Lobby"},{id:"garden",x:250,y:285,type:"junction",name:"Jardins"},{id:"west",x:135,y:315,type:"junction",name:"Allée ouest"},{id:"pool",x:345,y:330,type:"junction",name:"Allée des piscines"},{id:"beach-path",x:345,y:455,type:"junction",name:"Allée de la plage"},
{id:"main-restaurant",placeSlug:"main-restaurant",x:150,y:190,type:"destination",name:"Restaurant principal",shortName:"Restaurant",category:"Restaurants",description:"Buffet principal"},{id:"la-pergola",placeSlug:"la-pergola",x:95,y:260,type:"destination",name:"La Pergola",category:"Restaurants",description:"Restaurant à thème"},{id:"lobby-bar-obsolut",placeSlug:"lobby-bar-obsolut",x:355,y:185,type:"destination",name:"Lobby Bar Obsolut",shortName:"Lobby Bar",category:"Bars",description:"Bar du lobby"},{id:"moorish-cafe",placeSlug:"moorish-cafe",x:410,y:240,type:"destination",name:"Café maure",category:"Bars",description:"Café traditionnel"},{id:"outdoor-pools",placeSlug:"outdoor-pools",x:360,y:365,type:"destination",name:"Piscines extérieures",shortName:"Piscines",category:"Piscines",description:"Piscines et solarium"},{id:"oxygen-pool-bar",placeSlug:"oxygen-pool-bar",x:445,y:345,type:"destination",name:"Bar piscine Oxygen",shortName:"Oxygen",category:"Bars",description:"Bar piscine saisonnier"},{id:"indoor-pool",placeSlug:"indoor-pool",x:95,y:365,type:"destination",name:"Piscine couverte",shortName:"Piscine indoor",category:"Piscines",description:"Piscine intérieure chauffée"},{id:"wellness",placeSlug:"wellness",x:75,y:425,type:"destination",name:"Espace bien-être",shortName:"Bien-être",category:"Services",description:"Espace détente"},{id:"fitness",placeSlug:"fitness",x:155,y:425,type:"destination",name:"Salle de sport",shortName:"Gym",category:"Activités",description:"Fitness et remise en forme"},{id:"kids-club",placeSlug:"kids-club",x:245,y:375,type:"destination",name:"Mini Club",category:"Activités",description:"Activités pour les enfants"},{id:"sol-sombra",placeSlug:"sol-sombra",x:245,y:500,type:"destination",name:"Sol & Sombra",category:"Bars",description:"Snack bar plage"},{id:"beach-restaurant-bar",placeSlug:"beach-restaurant-bar",x:430,y:505,type:"destination",name:"Restaurant & Bar plage",shortName:"Restaurant plage",category:"Restaurants",description:"Restaurant en bord de mer"},{id:"beach",placeSlug:"beach",x:345,y:565,type:"destination",name:"Plage",category:"Services",description:"Plage privée de l’hôtel"}
];
export const mapEdges:MapEdge[]=[
{from:"reception",to:"lobby",seconds:25,instruction:"Traversez le lobby"},{from:"lobby",to:"garden",seconds:35,instruction:"Continuez vers les jardins"},{from:"lobby",to:"main-restaurant",seconds:25,instruction:"Rejoignez le restaurant principal"},{from:"lobby",to:"lobby-bar-obsolut",seconds:25,instruction:"Restez dans le lobby"},{from:"garden",to:"west",seconds:35,instruction:"Prenez l’allée ouest"},{from:"west",to:"la-pergola",seconds:25,instruction:"Suivez l’allée vers La Pergola"},{from:"west",to:"indoor-pool",seconds:30,instruction:"Continuez vers la piscine couverte"},{from:"west",to:"fitness",seconds:35,instruction:"Suivez l’allée des activités"},{from:"west",to:"wellness",seconds:40,instruction:"Continuez vers l’espace bien-être"},{from:"garden",to:"pool",seconds:45,instruction:"Continuez vers les piscines extérieures"},{from:"garden",to:"kids-club",seconds:35,instruction:"Suivez l’allée vers le Mini Club"},{from:"pool",to:"outdoor-pools",seconds:20,instruction:"Entrez dans la zone piscine"},{from:"pool",to:"oxygen-pool-bar",seconds:30,instruction:"Contournez la piscine vers Oxygen"},{from:"pool",to:"moorish-cafe",seconds:40,instruction:"Suivez le chemin du café maure"},{from:"pool",to:"beach-path",seconds:55,instruction:"Suivez l’allée principale vers la plage"},{from:"beach-path",to:"beach",seconds:40,instruction:"Continuez jusqu’à la plage"},{from:"beach-path",to:"sol-sombra",seconds:30,instruction:"Prenez l’allée vers Sol & Sombra"},{from:"beach-path",to:"beach-restaurant-bar",seconds:35,instruction:"Continuez vers le restaurant de plage"}
];
export const nodeBySlug=(slug?:string)=>mapNodes.find(n=>n.placeSlug===slug);
